apiVersion: batch/v1
kind: Job
metadata:
  name: gitsetupjob
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: gitsetupjob
    spec:
      containers:
      - name: gitsetupjob
        image: akubicharm/centos-workshop-gitsetup
        command: ["/workspace/run.sh"]
      restartPolicy: Never
